---
- hosts: localhost
  connection: local
  vars:
    host_key_checking: False
    cloud_user_password: cloudstack
  tasks:
    - name: fetch container ssh port
      shell: docker port cloudstack 22 | cut -d ":" -f 2
      register: container_ssh_port
    - name: create new ansible inventory for container
      template: src=build/inventory.j2 dest=./hosts
    - name: ensure sshpass is installed (Arch)
      pacman: name=sshpass state=present
      sudo: true
      when: ansible_os_family == "Archlinux"
    - name: ensure sshpass is installed (Debian)
      apt: name=sshpass state=latest
      sudo: true
      when: ansible_os_family == "Debian"
    - name: ensure sshpass is installed (RedHat)
      yum: name=sshpass state=latest
      sudo: true
      when: ansible_os_family == "RedHat"
    - name: ensure sshpass is installed (SUSE)
      zypper: name=http://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/sshpass-1.05-1.2.x86_64.rpm state=present
      sudo: true
      when: ansible_os_family == "Suse"
    - name: ensure sshpass is installed (Arch)
      pacman: name=sshpass state=present
      sudo: true
      when: ansible_os_family == "Archlinux"